import { object_192 } from '../anonymous';
import { Recipient } from './Recipient';
export interface DeviceDetails {
    /**
     * 
     * @description Optional trusted client identifier for the device.
     */
    clientId: any;
    /**
     * 
     * @description Secret value for the device.
     */
    deviceSecret: any;
    /**
     * 
     * @description Form factor of the push device.
     */
    formFactor: any;
    /**
     * 
     * @description Unique identifier for the device generated by the device itself.
     */
    id: any;
    /**
     * 
     * @description Optional metadata object for this device. The metadata for a device may only be set by clients with push-admin privileges and will be used more extensively in the future with smart notifications.
     */
    metadata: object_192;
    /**
     * 
     * @description Platform of the push device.
     */
    platform: any;
    push_recipient: Recipient;
    /**
     * 
     * @description the current state of the push device.
     */
    readonly push_state: any;
}
